#!/usr/bin/python3
"""





#####################################################################
    

                        DO NOT EDIT THIS FILE


#####################################################################






"""
import unittest
from main import add
class Tests(unittest.TestCase):
    def test(self):
        self.assertEqual(add(8,9),17)

        
if __name__=='__main__':
    unittest.main()
